version: '2.4'
services:
  dev:
    image: dariuskt/esp-platformio
    ports:
      - '10.24.1.97:22:22'
    volumes:
      - './src:/home/project/src'
      - '/home/project/.ssh:/home/project/.ssh'
      - '/home/project/.Xauthority:/home/project/.Xauthority'
      - '/etc/ssh:/etc/ssh'
      - '/etc/gitconfig:/etc/gitconfig'
      - '/etc/environment:/etc/environment-vm:ro'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'https://github.com/makerspacelt/DimOClock.git'
      NFQ_PROJECT_GIT_BRANCH: develop
      NFQ_INIT_SCRIPT: tools/docker/develop_init.sh
      DISPLAY: $DISPLAY


volumes: {  }
networks:
  default:
    ipam:
      config:
        - subnet: 10.24.1.97/28

